"""Added missing fk

Revision ID: 5b90c33340d5
Revises: 39aae6051a69
Create Date: 2018-06-22 16:38:27.170895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b90c33340d5'
down_revision = '39aae6051a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('format_id', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_book_format_id_format'), 'book', 'format', ['format_id'], ['id'])
    op.create_foreign_key(op.f('fk_book_language_id_language'), 'book', 'language', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_book_language_id_language'), 'book', type_='foreignkey')
    op.drop_constraint(op.f('fk_book_format_id_format'), 'book', type_='foreignkey')
    op.drop_column('book', 'language_id')
    op.drop_column('book', 'format_id')
    # ### end Alembic commands ###
