"""Add basic authentication table

Revision ID: 13fcd037bb5f
Revises: 4efa7212a47a
Create Date: 2025-06-19 00:05:47.717291

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13fcd037bb5f"
down_revision = "4efa7212a47a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authentication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authentication")
    # ### end Alembic commands ###
