"""Soft delete

Revision ID: 4efa7212a47a
Revises: fix_many2many_table_columns
Create Date: 2025-06-02 01:09:50.223835

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4efa7212a47a"
down_revision = "fix_many2many_table_columns"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "author",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "book",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "format",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "genre",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "language",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "publisher",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "series",
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )

    op.drop_index(op.f("idx_author_first_name"), table_name="author")
    op.drop_index(op.f("idx_author_name"), table_name="author")
    op.drop_index(op.f("idx_book__format"), table_name="book")
    op.drop_index(op.f("idx_book_authors"), table_name="book_authors")
    op.drop_index(op.f("idx_book_authors__author"), table_name="book_authors")
    op.drop_index(op.f("idx_book_authors__book_idx"), table_name="book_authors")
    op.drop_index(op.f("idx_book_authors_book_idx"), table_name="book_authors")
    op.drop_index(op.f("idx_book_created_at"), table_name="book")
    op.drop_index(op.f("idx_book_genres"), table_name="book_genres")
    op.drop_index(op.f("idx_book_isbn"), table_name="book")
    op.drop_index(op.f("idx_book_languages"), table_name="book_languages")
    op.drop_index(op.f("idx_book_publishers"), table_name="book_publishers")
    op.drop_index(op.f("idx_book_released"), table_name="book")
    op.drop_index(op.f("idx_format_name"), table_name="format")
    op.drop_index(op.f("idx_genre_name"), table_name="genre")
    op.drop_index(op.f("idx_language_name"), table_name="language")
    op.drop_index(op.f("idx_publisher_name"), table_name="publisher")
    op.drop_index(op.f("idx_series_index__book_idx"), table_name="series_index")
    op.drop_index(op.f("idx_series_index__series"), table_name="series_index")
    op.drop_index(op.f("idx_series_name"), table_name="series")

    op.create_index(
        "idx_book_authors_idx", "book_authors", ["book_id", "idx"], unique=False
    )
    op.create_index("idx_book_uuid", "book", ["uuid"], unique=False)
    op.create_index(
        "idx_series_index_idx", "series_index", ["book_id", "idx"], unique=False
    )
    op.create_index("idx_series_name", "series", ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_series_index_idx", table_name="series_index")
    op.create_index(
        op.f("idx_series_index__series"),
        "series_index",
        ["series_id", "book_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_series_index__book_idx"),
        "series_index",
        ["book_id", "idx"],
        unique=False,
    )
    op.drop_index("idx_series_name", table_name="series")
    op.create_index(op.f("idx_series_name"), "series", ["name"], unique=1)
    op.drop_column("series", "deleted")
    op.create_index(op.f("idx_publisher_name"), "publisher", ["name"], unique=False)
    op.drop_column("publisher", "deleted")
    op.create_index(op.f("idx_language_name"), "language", ["name"], unique=False)
    op.drop_column("language", "deleted")
    op.create_index(op.f("idx_genre_name"), "genre", ["name"], unique=False)
    op.drop_column("genre", "deleted")
    op.create_index(op.f("idx_format_name"), "format", ["name"], unique=False)
    op.drop_column("format", "deleted")
    op.create_index(
        op.f("idx_book_publishers"), "book_publishers", ["publisher_id"], unique=False
    )
    op.create_index(
        op.f("idx_book_languages"), "book_languages", ["language_id"], unique=False
    )
    op.create_index(op.f("idx_book_genres"), "book_genres", ["genre_id"], unique=False)
    op.drop_index("idx_book_authors_idx", table_name="book_authors")
    op.create_index(
        op.f("idx_book_authors_book_idx"), "book_authors", ["book_id", "idx"], unique=1
    )
    op.create_index(
        op.f("idx_book_authors__book_idx"),
        "book_authors",
        ["book_id", "idx"],
        unique=False,
    )
    op.create_index(
        op.f("idx_book_authors__author"), "book_authors", ["author_id"], unique=False
    )
    op.create_index(op.f("idx_book_authors"), "book_authors", ["book_id"], unique=False)
    op.drop_index("idx_book_uuid", table_name="book")
    op.create_index(op.f("idx_book_released"), "book", ["released"], unique=False)
    op.create_index(op.f("idx_book_isbn"), "book", ["isbn"], unique=False)
    op.create_index(op.f("idx_book_created_at"), "book", ["created_at"], unique=False)
    op.create_index(op.f("idx_book__format"), "book", ["format_id"], unique=False)
    op.drop_column("book", "deleted")
    op.create_index(op.f("idx_author_name"), "author", ["name"], unique=False)
    op.create_index(
        op.f("idx_author_first_name"), "author", ["first_name"], unique=False
    )
    op.drop_column("author", "deleted")
    # ### end Alembic commands ###
